// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pulsar.Resources.Database;

namespace Pulsar.Migrations
{
    [DbContext(typeof(PulsarDbContext))]
    [Migration("20181228173441_DataMigration")]
    partial class DataMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Pulsar.Resources.Datatypes.Inventory", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<ulong>("ItemID");

                    b.Property<ulong>("ServerID");

                    b.HasKey("UserID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Pulsar.Resources.Datatypes.Item", b =>
                {
                    b.Property<ulong>("ItemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ItemDescription");

                    b.Property<string>("ItemName");

                    b.Property<ulong>("ServerID");

                    b.HasKey("ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Pulsar.Resources.Datatypes.Member", b =>
                {
                    b.Property<ulong>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<ulong>("ServerID");

                    b.HasKey("UserID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Pulsar.Resources.Datatypes.Server", b =>
                {
                    b.Property<ulong>("ServerID")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("AdminRole");

                    b.Property<bool>("EnableModlog");

                    b.Property<bool>("LogBans");

                    b.Property<bool>("LogChannels");

                    b.Property<bool>("LogJoins");

                    b.Property<bool>("LogKicks");

                    b.Property<bool>("LogLeaves");

                    b.Property<bool>("LogMessageEdit");

                    b.Property<bool>("LogMessagedelete");

                    b.Property<bool>("LogRoles");

                    b.Property<bool>("LogServer");

                    b.Property<bool>("LogUserChanges");

                    b.Property<bool>("ModLogEmbed");

                    b.Property<ulong>("ModRole");

                    b.HasKey("ServerID");

                    b.ToTable("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
